// Registers bridge/host.js as a Chrome native messaging host, so the extension's "Start bridge"
// button can actually start the bridge. Same shape as hooks.js: a plain module that throws
// readable sentences, is idempotent, and is testable against a fake root directory.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { DATA_DIR } from "./store.js";

export const HOST_NAME = "com.pinpoint.bridge";
const HERE = path.dirname(fileURLToPath(import.meta.url));

// Chrome derives an extension's id from its manifest "key": sha256 of the DER public key, first
// 16 bytes, hex, with 0-f mapped onto a-p. Reading it from the manifest means the id can never
// drift out of sync with what is actually loaded.
export function extensionId(key) {
  const hex = crypto.createHash("sha256").update(Buffer.from(key, "base64")).digest("hex").slice(0, 32);
  return [...hex].map((c) => String.fromCharCode(97 + parseInt(c, 16))).join("");
}

// Browser profile roots. Detection is "the browser's own directory exists" — we create only the
// NativeMessagingHosts leaf inside it, never the browser directory, because its absence is the
// only signal that the browser is not installed.
const BROWSERS = {
  darwin: {
    base: path.join(os.homedir(), "Library", "Application Support"),
    dirs: {
      Chrome: "Google/Chrome", "Chrome Beta": "Google/Chrome Beta", "Chrome Canary": "Google/Chrome Canary",
      Chromium: "Chromium", Brave: "BraveSoftware/Brave-Browser", Edge: "Microsoft Edge",
      Arc: "Arc/User Data", Vivaldi: "Vivaldi", Opera: "com.operasoftware.Opera",
    },
  },
  linux: {
    base: path.join(os.homedir(), ".config"),
    dirs: {
      Chrome: "google-chrome", "Chrome Beta": "google-chrome-beta", Chromium: "chromium",
      Brave: "BraveSoftware/Brave-Browser", Edge: "microsoft-edge", Vivaldi: "vivaldi",
    },
  },
};

function wrapperScript({ node, hostPath, project, home }) {
  const env = [];
  if (project) env.push(`PINPOINT_PROJECT='${project}'; export PINPOINT_PROJECT`);
  if (home) env.push(`PINPOINT_HOME='${home}'; export PINPOINT_HOME`);
  // A browser-launched process inherits launchd's PATH — no shell rc, no nvm shims — so `exec node`
  // would simply not find node. The absolute path is baked in here at install time instead.
  // Nothing in this file may print to stdout: stdout is the native messaging stream.
  return `#!/bin/sh
# Generated by: node ${path.join(HERE, "cli.js")} install-native-host
# Re-run that after moving the repo or changing node.
# NOTHING may write to stdout from here — stdout is the native messaging stream.
${env.join("\n")}${env.length ? "\n" : ""}for n in '${node}' /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
  [ -x "$n" ] && exec "$n" '${hostPath}' "$@"
done
exit 78
`;
}

function targets(root, platform) {
  const table = BROWSERS[platform];
  if (!table) return null;
  const base = root || table.base;
  return Object.entries(table.dirs)
    .filter(([, rel]) => fs.existsSync(path.join(base, rel)))
    .map(([name, rel]) => ({ name, file: path.join(base, rel, "NativeMessagingHosts", `${HOST_NAME}.json`) }));
}

// How to reach each browser from a terminal: its macOS app name, its Linux binaries, and the page
// where "Load unpacked" lives. Keyed by the same names as BROWSERS above.
export const BROWSER_UI = {
  Chrome: { app: "Google Chrome", bin: ["google-chrome", "google-chrome-stable"], url: "chrome://extensions" },
  "Chrome Beta": { app: "Google Chrome Beta", bin: ["google-chrome-beta"], url: "chrome://extensions" },
  "Chrome Canary": { app: "Google Chrome Canary", bin: [], url: "chrome://extensions" },
  Chromium: { app: "Chromium", bin: ["chromium", "chromium-browser"], url: "chrome://extensions" },
  Brave: { app: "Brave Browser", bin: ["brave-browser", "brave"], url: "brave://extensions" },
  Edge: { app: "Microsoft Edge", bin: ["microsoft-edge", "microsoft-edge-stable"], url: "edge://extensions" },
  Arc: { app: "Arc", bin: [], url: "chrome://extensions" },
  Vivaldi: { app: "Vivaldi", bin: ["vivaldi", "vivaldi-stable"], url: "vivaldi://extensions" },
  Opera: { app: "Opera", bin: ["opera"], url: "opera://extensions" },
};

// Which Chromium browsers are actually installed. Same detection as the native host install — a
// browser is present if its profile directory is — so setup offers exactly the browsers that can
// take the extension, and an empty list is an answer rather than a crash.
export function detectBrowsers({ platform = process.platform, root = null } = {}) {
  return (targets(root, platform) || []).map((t) => ({ name: t.name, ...(BROWSER_UI[t.name] || {}) }));
}

export function installNativeHost({
  root = null,
  platform = process.platform,
  manifestPath = path.join(HERE, "..", "extension", "manifest.json"),
  hostPath = path.join(HERE, "host.js"),
  wrapperPath = path.join(DATA_DIR, "pinpoint-host.sh"),
  node = process.execPath,
  ids = [],
  project = process.env.PINPOINT_PROJECT || null,
  home = process.env.PINPOINT_HOME || null,
  uninstall = false,
} = {}) {
  if (!BROWSERS[platform]) {
    throw new Error(`native messaging install is macOS and Linux only for now — on Windows, start the bridge in a terminal: node ${path.join(HERE, "cli.js")}`);
  }
  const found = targets(root, platform);
  if (!found.length) {
    throw new Error(`no Chromium-based browser profile found under ${root || BROWSERS[platform].base} — is Chrome installed and has it been run once?`);
  }

  if (uninstall) {
    const removed = [];
    for (const t of found) if (fs.existsSync(t.file)) { fs.rmSync(t.file); removed.push(t.file); }
    if (fs.existsSync(wrapperPath)) { fs.rmSync(wrapperPath); removed.push(wrapperPath); }
    return { removed, browsers: [], files: [], message: removed.length ? `removed ${removed.length} file(s)` : "nothing to remove" };
  }

  let manifest;
  try { manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")); }
  catch { throw new Error(`could not read ${manifestPath} — run this from the pinpoint checkout`); }
  if (!manifest.key) throw new Error(`${manifestPath} has no "key", so the extension's id is not stable — pass --id <extension id> instead`);
  const wanted = [extensionId(manifest.key), ...ids];

  fs.mkdirSync(path.dirname(wrapperPath), { recursive: true });
  fs.writeFileSync(wrapperPath, wrapperScript({ node, hostPath, project, home }));
  fs.chmodSync(wrapperPath, 0o755);

  const files = [];
  for (const t of found) {
    // Union rather than replace: a second checkout registering itself must not evict the first.
    let origins = wanted.map((id) => `chrome-extension://${id}/`);
    try {
      const prev = JSON.parse(fs.readFileSync(t.file, "utf8"));
      if (Array.isArray(prev.allowed_origins)) origins = [...new Set([...prev.allowed_origins, ...origins])];
    } catch {}
    fs.mkdirSync(path.dirname(t.file), { recursive: true });
    fs.writeFileSync(t.file, JSON.stringify({
      name: HOST_NAME,
      description: "Starts the Pinpoint bridge for the Pinpoint browser extension",
      path: wrapperPath,
      type: "stdio",
      allowed_origins: [...origins].sort(),
    }, null, 2) + "\n");
    files.push(t.file);
  }

  return {
    files,
    browsers: found.map((t) => t.name),
    wrapperPath,
    node,
    ids: wanted,
    message: `The "Start bridge" button will now work in ${found.map((t) => t.name).join(", ")}.`,
  };
}
